# Site settings
title: IEEE NVMSA 2026

url: https://nvmsa2026.github.io/
baseurl: ''

conference_title: "The 15th Non-Volatile Memory Systems and Applications Symposium"
conference_title_short: "NVMSA"
year: "2026"
infoline_text: "Welcome to IEEE NVMSA 2026!"

# Color settings
color:
  primary-dark: '#3D1419'
  title: '#ebf0f4'
  links: '#219ab3'
  accent: '#B89E8F'

# conference data
background-image: img/afa2_desert_iso.png
directions-link: .\Introduction to Huanghai Hotel.pdf
#map-embed: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3302.323048471302!2d-118.12734598467776!3d34.13807638058268!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c4a7f5e60b13%3A0xc12af3fcb43bc03d!2sRamo+Auditorium!5e0!3m2!1sen!2sus!4v1546639172046
map-embed: https://maps.google.com/maps?hl=en&amp;q=黄海饭店&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed
organizer-email : organizer@email.com
registration-page : http://registration.com
upload-form: http://paperupload.com

collections:
  - invited_speakers
  - organizers_general
  - organizers_program
  - organizers_local
  - organizers_finance
  - organizers_registration
  - organizers_publicity
  - organizers_publication
  - organizers_web
  - sessions
  - papers

# Build settings
markdown: kramdown
permalink: pretty
